In [3]:
# %% imports
# libraries
import torch
from torch.utils.data import Dataset,DataLoader
import torch.optim as optim
import torch.nn as nn
from tqdm import tqdm
import matplotlib.pyplot as plt
import glob
import os
import numpy as np

# local imports
import MNIST_dataloader
# import autoencoder_template
from config_file import data_loc
from matplotlib import pyplot as plt
from MNIST_dataloader import create_dataloaders

# Week 1

### Exercise 1 - ISTA

##### (a)[3 pt]Create a Python function that implements ISTA for MNIST denoising. 
Make sure the function takes as inputs: step size μ, shrinkage parameter λ, number of
iteration K, and measurements (batch of MNIST images) y. It should output the
final batch of reconstructions xK.

hint: the images are normalized between -1 and 1, which means the background of the
images is not at zero. Think about how to still aply ISTA correctly.

In [7]:
########## Define Paramters
mu = 1e-4       # Step-size
shrinkage = 0   # 
K = 10          # Amount of itereations

In [4]:
### prepare the datasets
# get dataloader
batch_size = 64
train_loader, test_loader, val_loader = create_dataloaders(data_loc, batch_size)

In [5]:
# %% ISTA
def softthreshold(x,shrinkage):
    '''
    Implement soft threshold:
    F(x) = sign(x) * max(|x|)-lambda, 0_
    Arguments:
    ----------------------
    x: data-set (default: train_dataset)??
    shrinkage: float (default: --)
    '''
    new = torch.mul(torch.sign(x),torch.max(torch.abs(x)-shrinkage, 0))
    
    return new

def ISTA(mu,shrinkage,K,y):
    '''
    Iterative shrinkage and Thresholding Algorithm

    Arguments:
    --------------------
    mu:     float (default: 0.5)
        The stepsize

    shrinkage:  float (default: 0.5)
        The shrinking paramter
    
    K: int (default: 10)
        The number of unfolding iterations
    
    y: ??? (default: ???)
        The measurement image.

    Returns:
    --------------------
    x: ??? (default: ???)
        The denoised image    
    '''
    # initialize
    ##### Using flattened features
    # y2 = y.flatten()
    # x = torch.zeros_like(y2)
    # A = torch.eye(len(y2)) # length = WxH of image y

    #### Using non-flattend features
    y = y
    x = torch.empty_like(y)
    A = torch.eye(y)    
    # use for-loop for K-number of iterations
    for i in range(K):
        ### write the for-loop
    



    

    return

In [24]:
y = torch.Tensor(32, 32).uniform_(0, 225)
print(y)

tensor([[ 87.5784, 137.6103, 156.0368,  ..., 140.0040,  80.8602,  80.3002],
        [ 24.5583,  24.2110,  34.7155,  ...,   9.5193, 219.8152, 151.1400],
        [ 92.2112,  58.0858, 131.6390,  ..., 192.5061,  70.1760, 183.0031],
        ...,
        [  8.2174,  85.0267, 218.4816,  ...,  54.6934, 183.9227,  99.5359],
        [185.3454,  90.8415, 145.4967,  ..., 179.3370, 221.4976,  23.4768],
        [122.5168,  86.3312, 109.1421,  ...,  54.5471,  55.4464,  69.9607]])


In [35]:
z = y.flatten()
print(len(z))
shap = y.shape
print(shap)
A = torch.eye(y.shape[0])
print(A)
x = torch.empty(shap)
print(x.shape)


1024
torch.Size([32, 32])
tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])
torch.Size([32, 32])


In [39]:
# init params
mu = 0.5
lamda = 0.5
K = 10

y = y
x = torch.empty_like(y)
A = torch.eye(y.shape[0],y.shape[1])  

for i in range(K):
    p_init = (A@x - y)
    x_k = x + mu*p_init
    
    
      

tensor([[-7.5739e-31,  6.8664e-43, -7.5737e-31,  ...,  6.8664e-43,
         -3.9224e+31,  6.8664e-43],
        [-3.9223e+31,  6.8664e-43, -3.9223e+31,  ...,  6.8664e-43,
         -7.4770e-31,  6.8664e-43],
        [-7.4778e-31,  6.8664e-43, -7.4783e-31,  ...,  6.8664e-43,
         -7.4776e-31,  6.8664e-43],
        ...,
        [-7.3651e-31,  6.8664e-43, -7.3659e-31,  ...,  6.8664e-43,
         -7.3664e-31,  6.8664e-43],
        [-7.3658e-31,  6.8664e-43, -7.3648e-31,  ...,  6.8664e-43,
         -1.0468e+13,  6.8664e-43],
        [-1.0508e+13,  6.8664e-43, -6.4208e+11,  ...,  6.8664e-43,
         -1.0495e+13,  6.8664e-43]])


In [17]:
import numpy as np
 
# input two matrices
mat1 = np.array(([1, 6, 5],[3 ,4, 8],[2, 12, 3]))
mat2 = np.array(([3, 4, 6],[5, 6, 7],[6,56, 7]))
xx = np.array(([1, 0, 2]))
# This will return matrix product of two array
res = mat1 @ mat2
 
# print resulted matrix
print(xx)
print(mat1)
print(xx - mat1)

[1 0 2]
[[ 1  6  5]
 [ 3  4  8]
 [ 2 12  3]]
[[  0  -6  -3]
 [ -2  -4  -6]
 [ -1 -12  -1]]


##### (b) [2 pt] Use your ISTA algorithm on 10 example images. 
Show them in a figure consisting of 10 collumns (1 per digit) and 3 rows. Row 1 should contain the noisy
measurement, row 2 the reconstruction, and row 3 the actual ground truth target.
You will have to play with the values for μ, λ, and K. Explain what you see.

##### (c) [1 pt] To get a numerical estimate for the performance of ISTA, run it on the entire test set and report the resulting mean squared error (mse).